server.port=8083

razorpay.keyId=${RAZORPAY_KEY_ID:rzp_test_SYwvJpnDcJEIvZ}
razorpay.keySecret=${RAZORPAY_KEY_SECRET:acXTG6sTD8L4eAgoKbxwHmzF}
razorpay.companyName=${RAZORPAY_COMPANY_NAME:CoLive Connect}
razorpay.webhookSecret=${RAZORPAY_WEBHOOK_SECRET:}
razorpay.platformFee=${RAZORPAY_PLATFORM_FEE:4900}
razorpay.routeEnabled=${RAZORPAY_ROUTE_ENABLED:true}

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://root:StrongPassword!123@localhost:27017/admin}
spring.data.mongodb.database=${MONGODB_DATABASE:payments}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}
logging.level.javax.net.ssl=INFO
logging.level.sun.security.ssl=INFO
javax.net.ssl.trustStore=C:\ProjectSoftwares\Projects\elite4-main\payment-services\src\main\resources\cacerts.jks
javax.net.ssl.trustStorePassword=changeit
export JAVA_TOOL_OPTIONS="-Djavax.net.debug=ssl:handshake"
rest.client.connect.timeout=15
rest.client.read.timeout=60