server.port=8083

razorpay.keyId=${RAZORPAY_KEY_ID:rzp_test_SYwvJpnDcJEIvZ}
razorpay.keySecret=${RAZORPAY_KEY_SECRET:acXTG6sTD8L4eAgoKbxwHmzF}
razorpay.companyName=${RAZORPAY_COMPANY_NAME:CoLive Connect}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}
