server.port=8083

razorpay.keyId=${RAZORPAY_KEY_ID:YOUR_KEY_ID}
razorpay.keySecret=${RAZORPAY_KEY_SECRET:YOUR_KEY_SECRET}
razorpay.companyName=${RAZORPAY_COMPANY_NAME:CoLive Connect}

notification.service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8084}
