spring.application.name=resgistration-services
server.port=8082
mongodb.uri=mongodb://root:StrongPassword!123@localhost:27017/admin
mongodb.database=admin

# notification service base URL
notification.service.url=http://localhost:8084

